swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: 127.0.0.1:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /ticket:
    get:
      description: Retrieve tickets (filtering coming soon)
      responses:
        "200":
          description: Success
          schema:
            items:
              $ref: "#/definitions/TicketSearchResult"
    post:
      description: Creates a new ticket
      parameters:
        - name: title
          in: body
          description: Title for the ticket
          schema:
            $ref: "#/definitions/TicketCreationPayload"
      responses:
        "202":
          description: Created
          schema:
            $ref: "#/definitions/TicketCreationResponse"
# complex objects have schema definitions
definitions:
  TicketSearchResultItem:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      values:
        type: object
  TicketSearchResult:
    type: object
    properties:
      tickets: 
        type: array
        items:
          $ref: "#/definitions/TicketSearchResultItem"
  TicketCreationPayload:
    required:
      - title
    properties:
      title:
        type: string
      values:
        type: object
  TicketCreationResponse:
    required:
      - id
      - title
    properties:
      id:
        type: string
      title:
        type: string
      values:
        type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
